name: personal_fitness_tracker
description: Aplikasi Personal Fitness Tracker (Android & Web Preview)
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^9.0.0
  shared_preferences: ^2.2.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
